### ISSUE TITLE
Creating charges at interface

### ISSUE THREAD

**Issue by RenataLReis** [LeonardoESousa/KMC#16]
The function interface(), when called by the input file exciton_dissociation.py, returns KeyError: 'neigh'. This function is built at kmc/morphology.py 

`Traceback (most recent call last):
  File "/home/renata/.local/bin/kmc", line 11, in <module>
    load_entry_point('KMC==0.1.0', 'console_scripts', 'kmc')()
  File "/home/renata/.local/lib/python3.6/site-packages/kmc/__main__.py", line 262, in main
    ani = run_animation()
  File "/home/renata/.local/lib/python3.6/site-packages/kmc/__main__.py", line 244, in run_animation
    system = make_system()
  File "/home/renata/.local/lib/python3.6/site-packages/kmc/__main__.py", line 219, in make_system
    argumento.assign_to_system(system)
  File "/home/renata/.local/lib/python3.6/site-packages/kmc/morphology.py", line 45, in assign_to_system
    selected = self.method(range(len(system.X)),self.num, system, self.argv)
  File "/home/renata/.local/lib/python3.6/site-packages/kmc/morphology.py", line 20, in interface
    neighbors = kwargs['neigh']
KeyError: 'neigh'
`

**Comment by LeonardoESousa** [comment]
The interface function requires a keyword argument named neigh, which gives the number of nearest neighbors used in the search for interfacial sites. To use it, the GENERATE PARTICLES section should look like:

##GENERATE PARTICLES#####################################################################
method    = morphology.interface
exciton   = morphology.Create_Particles('singlet', 2, method, mat=[0,1], neigh=5)

#########################################################################################
